POST http://localhost/teste
Accept: application/json
Content-Type: application/json

{
    "listaComum": [
        1,
        2,
        3
    ],
    "dados": [
        {
            "id": 4,
            "colecao": [
                {
                    "produtoId": 5,
                    "preco": 5.25
                },
                {
                    "produtoId": 6,
                    "preco": 2.25
                },
                {
                    "produtoId": 5,
                    "preco": 7.25
                }
            ]
        }
    ]
}
