package regras;

import com.github.frkr.drlexec.*;
import com.example.*;

global com.github.frkr.drlexec.Retorno retorno;

rule "Teste MVEL"
dialect "mvel"
when
    x : Exemplo()
then
    retorno.getMsgs().add("Funciona: " + x.dados);
end

rule "Teste Java"
when
then
    retorno.getMsgs().add("Funciona: Java");
end

rule "Teste Lista"
when
    //vExemplo : Exemplo( vColecao : /dados/colecao[ produtoId == "5" ] )
    //Exemplo( vDados : /dados[ aColecao : /colecao[ produtoId == "5" ] ] )
    vaccumulate : Double() from accumulate(Exemplo( aColecao : /dados/colecao[ produtoId == "5" ] );,sum(aColecao.getPreco()))
then
//   retorno.getMsgs().add("Exemplo: " + vExemplo);
//   retorno.getMsgs().add("Colecao: " + vColecao);
//   retorno.getMsgs().add("aColecao: " + aColecao);
//   retorno.getMsgs().add("vDados: " + vDados);
   retorno.getMsgs().add("accumulate: " + vaccumulate);
end
